In [45]:
import numpy as np
from numpy import linalg as LA
from sympy import Matrix

**1. Select the characteristic polynomial for the given matrix.**

$$
\begin{bmatrix}
2 & 1 \\
-3 & 6
\end{bmatrix}
$$

In [46]:
Matrix(np.array([2, 1, -3, 6]).reshape((2, 2))).charpoly()

PurePoly(lambda**2 - 8*lambda + 15, lambda, domain='ZZ')

**2. Select the eigenvectors for the previous matrix in Q1, as given below:**

$$
\begin{bmatrix}
2 & 1 \\
-3 & 6
\end{bmatrix}
$$

In [47]:
w, v = LA.eig(np.array([2, 1, -3, 6]).reshape((2, 2)))
print(v)
# scale
np.append(
    v[:,0] / v[0,0],
    v[:,1] / v[0,1],
).reshape((2,2))




[[-0.70710678 -0.31622777]
 [-0.70710678 -0.9486833 ]]


array([[1., 1.],
       [1., 3.]])

**3. Which of the following is an eigenvalue for the given identity matrix.**

$$
ID = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

In [48]:
w, v = LA.eig(np.identity(3))
w

array([1., 1., 1.])

**4. Find the eigenvalues of matrix A⋅B where:**

$$
A = \begin{bmatrix}
1 & 2 \\
0 & 4
\end{bmatrix}
\\
$$
$$
\\
B = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
$$

_Hint: What type of matrix is B? Does it change the output when multiplied with A? If not, focus only on one of the matrices to find the eigenvalues._

In [72]:
A = np.array([1, 2, 0, 4]).reshape((2, 2))
w, v = LA.eig(A)
w

array([1., 4.])

**5. Select the eigenvectors, using the eigenvalues you found for the above matrix A⋅B in Q4.**

In [103]:
print(v)
np.append(
    v[:,0],
    v[:,1] / v[0,1] * 2,
).reshape((2,2)).T


[[1.         0.5547002 ]
 [0.         0.83205029]]


array([[1., 2.],
       [0., 3.]])

**6. Which of the vectors span the matrix**

$$
W = \begin{bmatrix}
2 & 3 & 0 \\
1 & 2 & 5 \\
3 & -2 & -1
\end{bmatrix}
$$

In [115]:
W = np.array([2, 3, 0, 1, 2, 5, 3, -2, -1]).reshape((3,3))
v1, v2, v3 = W[:,0], W[:,1], W[:,2]
print(v1, v2, v3)

[2 1 3] [ 3  2 -2] [ 0  5 -1]


**7. Given matrix P select the answer with the correct eigenbasis.**

$$
P = \begin{bmatrix}
2 & 0 & 0 \\
1 & 2 & 1 \\
-1 & 0 & 1
\end{bmatrix}
$$

_Hint: First compute the eigenvalues,  eigenvectors and construct the eigenbasis matrix with the spanning eigenvectors._

In [130]:
P = np.array([2, 0, 0, 1, 2, 1, -1, 0, 1]).reshape((3,3))
w, v = LA.eig(P)
print(v)
np.hstack([v[:,0].reshape((3,1)), v[:,1:] / v[0,2]])

[[ 0.          0.          0.70710678]
 [ 1.         -0.70710678  0.        ]
 [ 0.          0.70710678 -0.70710678]]


array([[ 0.,  0.,  1.],
       [ 1., -1.,  0.],
       [ 0.,  1., -1.]])

**8. Select the characteristic polynomial for the given matrix.**

$$
\begin{bmatrix}
3 & 1 & -2 \\
4 & 0 & 1 \\
2 & 1 & -1
\end{bmatrix}
$$

In [136]:
Matrix(np.array([3, 1, -2, 4, 0, 1, 2, 1, -1]).reshape((3,3))).charpoly()

PurePoly(lambda**3 - 2*lambda**2 - 4*lambda + 5, lambda, domain='ZZ')

**9. You are given a non-singular matrix A with real entries and eigenvalue $i$**

$1/i$ is an eigenvalue of $A^{-1}$