In [2]:
import numpy as np

In [22]:
# "array range"
a = np.arange(15).reshape(3, 5)

In [12]:
a.shape

(3, 5)

In [13]:
a.ndim

2

In [14]:
a.dtype.name

'int64'

In [15]:
a.size

15

In [16]:
type(a)

numpy.ndarray

In [18]:
np.array([6, 7, 8]).shape

(3,)

In [21]:
np.array([
    (1, 2, 3),
    (4, 5, 6)
])

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.arange(1, 22, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [33]:
# 9 numbers from 0 to 2
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
# 3d array
_ = np.arange(24).reshape(2, 3, 4)
print(_)
_.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [46]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])